### ISSUE TITLE
Energy Efficient dataset

### ISSUE THREAD

**Issue by caxelrud** [JavierAntoran/Bayesian-Neural-Networks#11]
For bbp_hetero notebook, the Energy Efficiency dataset has 8 inputs and 2 outputs.
At the moment, output 1 is being used as an input to model output 2.
You can just drop the last column of the dataset and model 8 inputs and 1 output.
I tried and worked fine.

**Comment by JavierAntoran** [comment]
Sure. This choice was made because generally, in the BNN literature, the one-output version of the dataset is used.
