### ISSUE TITLE
Looking for the implementation of "Getting a GlUE"

### ISSUE THREAD

**Issue by SuperHao-Wu** [JavierAntoran/Bayesian-Neural-Networks#18]
Hi @JavierAntoran ,
my name is Hao, I'm searching for a valid method for the Uncertainty Explanations, like to decompose the Uncertainty of the prediction back to the features, until I found your paper "Getting a GLUE: A Method for Explaining Uncertainty Estimates", and find it fantastic, do you have implementations of the "CLUE" in this repo or where can I find it, because I see the reference of this github in the paper? I'm researching on using ICU data to do Sepsis Prediction, really appreciate it if you can help.

Thanks in Advance 
Hao

**Comment by JavierAntoran** [comment]
Hey @SuperHao-Wu,

The code is now available at: https://github.com/cambridge-mlg/CLUE

Best,
Javier
