### ISSUE TITLE
bbp_hetero notebook is not using three layers

### ISSUE THREAD

**Issue by caxelrud** [JavierAntoran/Bayesian-Neural-Networks#7]
In the class BBP_Heteroscedastic_Model_UCI, three layers are declared but in the forward method layer3 calling is missing. I added and worked fine.

**Comment by JavierAntoran** [comment]
OK, thanks, good to know!

I think we might have used 2 layers to make our results comparable with (Hernández-Lobato and Adams, https://arxiv.org/pdf/1502.05336.pdf). It has become somewhat of a benchmark in the BNN community to test UCI datasets on single hidden layer MLPs. However, this benchmark has serious limitations as highlighted by (Foong et. al. https://arxiv.org/pdf/1909.00719)
